image: gitlab/gitlab-runner:alpine

stages:
  - build

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
    - ant build
  rules:
    - if: $CI_COMMIT_TAG
  artifacts:
    paths:
      - build/Heroes-public1.zip
      - build/Heroes-pack1.zip
      - build/Heroes-pack2.zip
      - build/Heroes-pack3.zip
      - build/Heroes-pack4.zip
      - build/Heroes-pack5.zip
      - build/Heroes-pack6.zip
      - build/Heroes-pack7.zip
      - build/Heroes-pack8.zip
      - build/Heroes-reborn.zip
      - build/Heroes-remastered.zip