image: openjdk:11

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build

build:
  stage: build
  script:
    - ./gradlew build-packs
  artifacts:
    paths:
      - build/Heroes-public1.zip
      - build/Heroes-pack1.zip
      - build/Heroes-pack2.zip
      - build/Heroes-pack3.zip
      - build/Heroes-pack4.zip
      - build/Heroes-pack5.zip
      - build/Heroes-pack6.zip
      - build/Heroes-pack7.zip
      - build/Heroes-pack8.zip
      - build/Heroes-reborn.zip
      - build/Heroes-remastered.zip